PATH_SOCKS_BIN = 'ChristmasSocks/bin/socks'

TCP_PORT = 8080
IPV4_ADDRESS_SERVER = '127.0.0.1'
TCP_BUFFER_SIZE = 1024
SOCK_TIMEOUT = 1.5
MAX_CONNECTION_ATTEMPTS = 25

SERVER_SHUTDOWN_DELAY = 0.05
SERVER_VALGRIND_STARTUP_DELAY = 5
STARTUP_DELAY_VALGRIND = 5
